// Generated by protocol/generate.py from protocol/schema.json. Do not edit.
export const PROTOCOL_VERSION = 2 as const;

export interface HelloRequest {
  type: "hello";
  protocol_version: 2;
  request_id: string;
}

export interface GetConfigRequest {
  type: "get_config";
  protocol_version: 2;
  request_id: string;
}

export interface UpdateConfigRequest {
  type: "update_config";
  protocol_version: 2;
  request_id: string;
  expected_revision: string;
  config: ConfigSnapshot;
  picker_token: string | null;
  consent_token: string | null;
}

export interface HelloResult {
  type: "hello_result";
  protocol_version: 2;
  request_id: string;
  host_version: string;
  configured: boolean;
  config_issue: string | null;
}

export interface ConfigResult {
  type: "config_result";
  protocol_version: 2;
  request_id: string;
  revision: string;
  config: ConfigSnapshot;
  config_issue: string | null;
}

export interface ConfigUpdated {
  type: "config_updated";
  protocol_version: 2;
  request_id: string;
  revision: string;
  config: ConfigSnapshot;
}

export interface ErrorResponse {
  type: "error";
  protocol_version: 2;
  request_id: string;
  code: ErrorCode;
  message: string;
}

export type ErrorCode = "invalid_request" | "unsupported_protocol_version" | "invalid_config" | "not_configured" | "unauthorized" | "conflict" | "message_too_large" | "internal" | "cancelled";

export interface ConfigSnapshot {
  storage: StorageConfig | null;
  capture_enabled: boolean;
  sites: SiteConfig[];
  strip_params: string[];
  near_repeat_secs: number;
}

export interface StorageConfig {
  root: string;
  profile: string;
  log_dir: string;
  pages_dir: string;
  later_dir: string;
}

export interface ChooseFolderRequest {
  type: "choose_folder";
  protocol_version: 2;
  request_id: string;
}

export interface ConfirmConfigRequest {
  type: "confirm_config";
  protocol_version: 2;
  request_id: string;
  expected_revision: string;
  config: ConfigSnapshot;
  picker_token: string | null;
}

export interface RecordVisitRequest {
  type: "record_visit";
  protocol_version: 2;
  request_id: string;
  event: VisitEvent;
}

export interface CreatePageNoteRequest {
  type: "create_page_note";
  protocol_version: 2;
  request_id: string;
  url: string;
  title: string;
  body: string;
}

export interface FolderChosen {
  type: "folder_chosen";
  protocol_version: 2;
  request_id: string;
  path: string;
  picker_token: string;
}

export interface ConfigConfirmed {
  type: "config_confirmed";
  protocol_version: 2;
  request_id: string;
  consent_token: string;
  summary: string;
}

export interface VisitRecorded {
  type: "visit_recorded";
  protocol_version: 2;
  request_id: string;
  event_id: string;
  outcome: VisitOutcome;
  reason: string | null;
  relative_path: string | null;
}

export interface PageNoteResult {
  type: "page_note_result";
  protocol_version: 2;
  request_id: string;
  outcome: PageNoteOutcome;
  relative_path: string | null;
  message: string | null;
}

export interface SiteConfig {
  origin: string;
  path_prefix: string;
}

export interface VisitEvent {
  event_id: string;
  url: string;
  title: string | null;
  occurred_at: string;
  incognito: boolean;
}

export type VisitOutcome = "persisted" | "suppressed" | "rejected" | "retryable";

export type PageNoteOutcome = "created" | "already_present" | "conflict" | "created_with_warning";

export type Request = HelloRequest | GetConfigRequest | UpdateConfigRequest | ChooseFolderRequest | ConfirmConfigRequest | RecordVisitRequest | CreatePageNoteRequest;

export type Response = HelloResult | ConfigResult | ConfigUpdated | FolderChosen | ConfigConfirmed | VisitRecorded | PageNoteResult | ErrorResponse;
