// Generated by protocol/generate.py from protocol/schema.json. Do not edit.
export const PROTOCOL_VERSION = 4 as const;

export interface HelloRequest {
  type: "hello";
  protocol_version: 4;
  request_id: string;
}

export interface GetConfigRequest {
  type: "get_config";
  protocol_version: 4;
  request_id: string;
}

export interface UpdateConfigRequest {
  type: "update_config";
  protocol_version: 4;
  request_id: string;
  expected_revision: string;
  config: ConfigSnapshot;
  picker_token: string | null;
  consent_token: string | null;
  harness_token: string | null;
}

export interface HelloResult {
  type: "hello_result";
  protocol_version: 4;
  request_id: string;
  host_version: string;
  configured: boolean;
  config_issue: string | null;
}

export interface ConfigResult {
  type: "config_result";
  protocol_version: 4;
  request_id: string;
  revision: string;
  config: ConfigSnapshot;
  config_issue: string | null;
  agent_status: AgentStatus;
}

export interface ConfigUpdated {
  type: "config_updated";
  protocol_version: 4;
  request_id: string;
  revision: string;
  config: ConfigSnapshot;
}

export interface ErrorResponse {
  type: "error";
  protocol_version: 4;
  request_id: string;
  code: ErrorCode;
  message: string;
}

export type ErrorCode = "invalid_request" | "unsupported_protocol_version" | "invalid_config" | "not_configured" | "unauthorized" | "conflict" | "message_too_large" | "internal" | "cancelled";

export interface ConfigSnapshot {
  storage: StorageConfig | null;
  capture_enabled: boolean;
  sites: SiteConfig[];
  strip_params: string[];
  near_repeat_secs: number;
  agent_denylist: string[];
  agent_denylist_confirmed: boolean;
  log_incognito: boolean;
  agent: AgentConfig | null;
}

export interface StorageConfig {
  root: string;
  profile: string;
  log_dir: string;
  pages_dir: string;
  later_dir: string;
  summaries_dir: string | null;
}

export interface AgentConfig {
  harness_id: string;
  adapter: HarnessAdapter;
  binary: string;
  args: string[];
  env_allow: string[];
  timeout_secs: number;
}

export type HarnessAdapter = "claude_code" | "codex";

export interface AgentStatus {
  state: AgentState;
  harness_version: string | null;
  message: string | null;
}

export type AgentState = "not_set_up" | "denylist_unconfirmed" | "harness_problem" | "ready";

export interface ChooseFolderRequest {
  type: "choose_folder";
  protocol_version: 4;
  request_id: string;
}

export interface ConfirmConfigRequest {
  type: "confirm_config";
  protocol_version: 4;
  request_id: string;
  expected_revision: string;
  config: ConfigSnapshot;
  picker_token: string | null;
}

export interface RecordVisitRequest {
  type: "record_visit";
  protocol_version: 4;
  request_id: string;
  event: VisitEvent;
}

export interface LoadNoteRequest {
  type: "load_note";
  protocol_version: 4;
  request_id: string;
  url: string;
}

export interface SaveNoteRequest {
  type: "save_note";
  protocol_version: 4;
  request_id: string;
  url: string;
  title: string;
  body: string;
  expected_revision: string;
}

export interface CheckAgentRequest {
  type: "check_agent";
  protocol_version: 4;
  request_id: string;
  url: string | null;
}

export interface FolderChosen {
  type: "folder_chosen";
  protocol_version: 4;
  request_id: string;
  path: string;
  picker_token: string;
}

export interface ConfigConfirmed {
  type: "config_confirmed";
  protocol_version: 4;
  request_id: string;
  consent_token: string;
  summary: string;
}

export interface VisitRecorded {
  type: "visit_recorded";
  protocol_version: 4;
  request_id: string;
  event_id: string;
  outcome: VisitOutcome;
  reason: string | null;
  relative_path: string | null;
}

export interface NoteLoaded {
  type: "note_loaded";
  protocol_version: 4;
  request_id: string;
  exists: boolean;
  revision: string;
  title: string;
  body: string;
}

export interface NoteSaved {
  type: "note_saved";
  protocol_version: 4;
  request_id: string;
  outcome: NoteSaveOutcome;
  revision: string;
  relative_path: string;
}

export interface NoteConflict {
  type: "note_conflict";
  protocol_version: 4;
  request_id: string;
  exists: boolean;
  revision: string;
  title: string;
  body: string;
}

export interface AgentChecked {
  type: "agent_checked";
  protocol_version: 4;
  request_id: string;
  harness_id: string;
  harness_version: string;
  url_allowed: boolean | null;
}

export interface SiteConfig {
  origin: string;
  path_prefix: string;
}

export interface VisitEvent {
  event_id: string;
  url: string;
  title: string | null;
  occurred_at: string;
  incognito: boolean;
}

export type VisitOutcome = "persisted" | "suppressed" | "rejected" | "retryable";

export type NoteSaveOutcome = "created" | "replaced" | "created_with_warning" | "replaced_with_warning";

export interface DiscoverHarnessesRequest {
  type: "discover_harnesses";
  protocol_version: 4;
  request_id: string;
  expected_revision: string;
}

export interface ConfirmHarnessSetupRequest {
  type: "confirm_harness_setup";
  protocol_version: 4;
  request_id: string;
  expected_revision: string;
  offer_id: string;
  env_names: string[];
  agent_denylist: string[];
  summaries_dir: string | null;
}

export interface HarnessesDiscovered {
  type: "harnesses_discovered";
  protocol_version: 4;
  request_id: string;
  offers: HarnessOffer[];
}

export interface HarnessSetupConfirmed {
  type: "harness_setup_confirmed";
  protocol_version: 4;
  request_id: string;
  harness_token: string;
  config: ConfigSnapshot;
  summary: string;
}

export interface HarnessOffer {
  offer_id: string | null;
  adapter: HarnessAdapter;
  harness_id: string;
  binary: string;
  real_path: string | null;
  version: string | null;
  args: string[];
  env_required: string[];
  env_optional: EnvName[];
  refusal: string | null;
}

export interface EnvName {
  name: string;
  present: boolean;
}

export type Request = HelloRequest | GetConfigRequest | UpdateConfigRequest | ChooseFolderRequest | ConfirmConfigRequest | RecordVisitRequest | LoadNoteRequest | SaveNoteRequest | CheckAgentRequest | DiscoverHarnessesRequest | ConfirmHarnessSetupRequest;

export type Response = HelloResult | ConfigResult | ConfigUpdated | FolderChosen | ConfigConfirmed | VisitRecorded | NoteLoaded | NoteSaved | NoteConflict | AgentChecked | HarnessesDiscovered | HarnessSetupConfirmed | ErrorResponse;
