// Generated by protocol/generate.py from protocol/schema.json. Do not edit.
use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 2;

// A nullable JSON Schema property is still required on the wire.
// Serde otherwise treats a missing Option field as None.
fn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GetConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub picker_token: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub consent_token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub host_version: String,
    pub configured: bool,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub config_issue: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub config_issue: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigUpdated {
    pub protocol_version: u32,
    pub request_id: String,
    pub revision: String,
    pub config: ConfigSnapshot,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ErrorResponse {
    pub protocol_version: u32,
    pub request_id: String,
    pub code: ErrorCode,
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidRequest,
    UnsupportedProtocolVersion,
    InvalidConfig,
    NotConfigured,
    Unauthorized,
    Conflict,
    MessageTooLarge,
    Internal,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigSnapshot {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub storage: Option<StorageConfig>,
    pub capture_enabled: bool,
    pub sites: Vec<SiteConfig>,
    pub strip_params: Vec<String>,
    pub near_repeat_secs: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StorageConfig {
    pub root: String,
    pub profile: String,
    pub log_dir: String,
    pub pages_dir: String,
    pub later_dir: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ChooseFolderRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfirmConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub picker_token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordVisitRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub event: VisitEvent,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CreatePageNoteRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub url: String,
    pub title: String,
    pub body: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FolderChosen {
    pub protocol_version: u32,
    pub request_id: String,
    pub path: String,
    pub picker_token: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigConfirmed {
    pub protocol_version: u32,
    pub request_id: String,
    pub consent_token: String,
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VisitRecorded {
    pub protocol_version: u32,
    pub request_id: String,
    pub event_id: String,
    pub outcome: VisitOutcome,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub reason: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub relative_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PageNoteResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub outcome: PageNoteOutcome,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub relative_path: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SiteConfig {
    pub origin: String,
    pub path_prefix: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VisitEvent {
    pub event_id: String,
    pub url: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub title: Option<String>,
    pub occurred_at: String,
    pub incognito: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VisitOutcome {
    Persisted,
    Suppressed,
    Rejected,
    Retryable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PageNoteOutcome {
    Created,
    AlreadyPresent,
    Conflict,
    CreatedWithWarning,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Request {
    Hello(HelloRequest),
    GetConfig(GetConfigRequest),
    UpdateConfig(UpdateConfigRequest),
    ChooseFolder(ChooseFolderRequest),
    ConfirmConfig(ConfirmConfigRequest),
    RecordVisit(RecordVisitRequest),
    CreatePageNote(CreatePageNoteRequest),
}

impl Request {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::Hello(value) => value.protocol_version,
            Self::GetConfig(value) => value.protocol_version,
            Self::UpdateConfig(value) => value.protocol_version,
            Self::ChooseFolder(value) => value.protocol_version,
            Self::ConfirmConfig(value) => value.protocol_version,
            Self::RecordVisit(value) => value.protocol_version,
            Self::CreatePageNote(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::Hello(value) => &value.request_id,
            Self::GetConfig(value) => &value.request_id,
            Self::UpdateConfig(value) => &value.request_id,
            Self::ChooseFolder(value) => &value.request_id,
            Self::ConfirmConfig(value) => &value.request_id,
            Self::RecordVisit(value) => &value.request_id,
            Self::CreatePageNote(value) => &value.request_id,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Response {
    HelloResult(HelloResult),
    ConfigResult(ConfigResult),
    ConfigUpdated(ConfigUpdated),
    FolderChosen(FolderChosen),
    ConfigConfirmed(ConfigConfirmed),
    VisitRecorded(VisitRecorded),
    PageNoteResult(PageNoteResult),
    Error(ErrorResponse),
}

impl Response {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::HelloResult(value) => value.protocol_version,
            Self::ConfigResult(value) => value.protocol_version,
            Self::ConfigUpdated(value) => value.protocol_version,
            Self::FolderChosen(value) => value.protocol_version,
            Self::ConfigConfirmed(value) => value.protocol_version,
            Self::VisitRecorded(value) => value.protocol_version,
            Self::PageNoteResult(value) => value.protocol_version,
            Self::Error(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::HelloResult(value) => &value.request_id,
            Self::ConfigResult(value) => &value.request_id,
            Self::ConfigUpdated(value) => &value.request_id,
            Self::FolderChosen(value) => &value.request_id,
            Self::ConfigConfirmed(value) => &value.request_id,
            Self::VisitRecorded(value) => &value.request_id,
            Self::PageNoteResult(value) => &value.request_id,
            Self::Error(value) => &value.request_id,
        }
    }
}
