// Generated by protocol/generate.py from protocol/schema.json. Do not edit.
use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GetConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub config: ConfigSnapshot,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub host_version: String,
    pub configured: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub config: ConfigSnapshot,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigUpdated {
    pub protocol_version: u32,
    pub request_id: String,
    pub config: ConfigSnapshot,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ErrorResponse {
    pub protocol_version: u32,
    pub request_id: String,
    pub code: ErrorCode,
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidRequest,
    UnsupportedProtocolVersion,
    InvalidConfig,
    NotConfigured,
    Unauthorized,
    Conflict,
    MessageTooLarge,
    Internal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigSnapshot {
    pub storage: Option<StorageConfig>,
    pub capture_enabled: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StorageConfig {
    pub root: String,
    pub profile: String,
    pub log_dir: String,
    pub pages_dir: String,
    pub later_dir: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Request {
    Hello(HelloRequest),
    GetConfig(GetConfigRequest),
    UpdateConfig(UpdateConfigRequest),
}

impl Request {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::Hello(value) => value.protocol_version,
            Self::GetConfig(value) => value.protocol_version,
            Self::UpdateConfig(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::Hello(value) => &value.request_id,
            Self::GetConfig(value) => &value.request_id,
            Self::UpdateConfig(value) => &value.request_id,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Response {
    HelloResult(HelloResult),
    ConfigResult(ConfigResult),
    ConfigUpdated(ConfigUpdated),
    Error(ErrorResponse),
}

impl Response {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::HelloResult(value) => value.protocol_version,
            Self::ConfigResult(value) => value.protocol_version,
            Self::ConfigUpdated(value) => value.protocol_version,
            Self::Error(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::HelloResult(value) => &value.request_id,
            Self::ConfigResult(value) => &value.request_id,
            Self::ConfigUpdated(value) => &value.request_id,
            Self::Error(value) => &value.request_id,
        }
    }
}
