// Generated by protocol/generate.py from protocol/schema.json. Do not edit.
use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 4;

// A nullable JSON Schema property is still required on the wire.
// Serde otherwise treats a missing Option field as None.
fn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GetConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpdateConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub picker_token: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub consent_token: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub harness_token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub host_version: String,
    pub configured: bool,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub config_issue: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigResult {
    pub protocol_version: u32,
    pub request_id: String,
    pub revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub config_issue: Option<String>,
    pub agent_status: AgentStatus,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigUpdated {
    pub protocol_version: u32,
    pub request_id: String,
    pub revision: String,
    pub config: ConfigSnapshot,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ErrorResponse {
    pub protocol_version: u32,
    pub request_id: String,
    pub code: ErrorCode,
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidRequest,
    UnsupportedProtocolVersion,
    InvalidConfig,
    NotConfigured,
    Unauthorized,
    Conflict,
    MessageTooLarge,
    Internal,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigSnapshot {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub storage: Option<StorageConfig>,
    pub capture_enabled: bool,
    pub sites: Vec<SiteConfig>,
    pub strip_params: Vec<String>,
    pub near_repeat_secs: u32,
    pub agent_denylist: Vec<String>,
    pub agent_denylist_confirmed: bool,
    pub log_incognito: bool,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub agent: Option<AgentConfig>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StorageConfig {
    pub root: String,
    pub profile: String,
    pub log_dir: String,
    pub pages_dir: String,
    pub later_dir: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub summaries_dir: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentConfig {
    pub harness_id: String,
    pub adapter: HarnessAdapter,
    pub binary: String,
    pub args: Vec<String>,
    pub env_allow: Vec<String>,
    pub timeout_secs: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HarnessAdapter {
    ClaudeCode,
    Codex,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentStatus {
    pub state: AgentState,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub harness_version: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub message: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentState {
    NotSetUp,
    DenylistUnconfirmed,
    HarnessProblem,
    Ready,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ChooseFolderRequest {
    pub protocol_version: u32,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfirmConfigRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
    pub config: ConfigSnapshot,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub picker_token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordVisitRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub event: VisitEvent,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LoadNoteRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub url: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SaveNoteRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub url: String,
    pub title: String,
    pub body: String,
    pub expected_revision: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CheckAgentRequest {
    pub protocol_version: u32,
    pub request_id: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub url: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FolderChosen {
    pub protocol_version: u32,
    pub request_id: String,
    pub path: String,
    pub picker_token: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigConfirmed {
    pub protocol_version: u32,
    pub request_id: String,
    pub consent_token: String,
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VisitRecorded {
    pub protocol_version: u32,
    pub request_id: String,
    pub event_id: String,
    pub outcome: VisitOutcome,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub reason: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub relative_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NoteLoaded {
    pub protocol_version: u32,
    pub request_id: String,
    pub exists: bool,
    pub revision: String,
    pub title: String,
    pub body: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NoteSaved {
    pub protocol_version: u32,
    pub request_id: String,
    pub outcome: NoteSaveOutcome,
    pub revision: String,
    pub relative_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NoteConflict {
    pub protocol_version: u32,
    pub request_id: String,
    pub exists: bool,
    pub revision: String,
    pub title: String,
    pub body: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentChecked {
    pub protocol_version: u32,
    pub request_id: String,
    pub harness_id: String,
    pub harness_version: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub url_allowed: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SiteConfig {
    pub origin: String,
    pub path_prefix: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VisitEvent {
    pub event_id: String,
    pub url: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub title: Option<String>,
    pub occurred_at: String,
    pub incognito: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VisitOutcome {
    Persisted,
    Suppressed,
    Rejected,
    Retryable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NoteSaveOutcome {
    Created,
    Replaced,
    CreatedWithWarning,
    ReplacedWithWarning,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DiscoverHarnessesRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfirmHarnessSetupRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub expected_revision: String,
    pub offer_id: String,
    pub env_names: Vec<String>,
    pub agent_denylist: Vec<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub summaries_dir: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HarnessesDiscovered {
    pub protocol_version: u32,
    pub request_id: String,
    pub offers: Vec<HarnessOffer>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HarnessSetupConfirmed {
    pub protocol_version: u32,
    pub request_id: String,
    pub harness_token: String,
    pub config: ConfigSnapshot,
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HarnessOffer {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub offer_id: Option<String>,
    pub adapter: HarnessAdapter,
    pub harness_id: String,
    pub binary: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub real_path: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub version: Option<String>,
    pub args: Vec<String>,
    pub env_required: Vec<String>,
    pub env_optional: Vec<EnvName>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    pub refusal: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvName {
    pub name: String,
    pub present: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Request {
    Hello(HelloRequest),
    GetConfig(GetConfigRequest),
    UpdateConfig(UpdateConfigRequest),
    ChooseFolder(ChooseFolderRequest),
    ConfirmConfig(ConfirmConfigRequest),
    RecordVisit(RecordVisitRequest),
    LoadNote(LoadNoteRequest),
    SaveNote(SaveNoteRequest),
    CheckAgent(CheckAgentRequest),
    DiscoverHarnesses(DiscoverHarnessesRequest),
    ConfirmHarnessSetup(ConfirmHarnessSetupRequest),
}

impl Request {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::Hello(value) => value.protocol_version,
            Self::GetConfig(value) => value.protocol_version,
            Self::UpdateConfig(value) => value.protocol_version,
            Self::ChooseFolder(value) => value.protocol_version,
            Self::ConfirmConfig(value) => value.protocol_version,
            Self::RecordVisit(value) => value.protocol_version,
            Self::LoadNote(value) => value.protocol_version,
            Self::SaveNote(value) => value.protocol_version,
            Self::CheckAgent(value) => value.protocol_version,
            Self::DiscoverHarnesses(value) => value.protocol_version,
            Self::ConfirmHarnessSetup(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::Hello(value) => &value.request_id,
            Self::GetConfig(value) => &value.request_id,
            Self::UpdateConfig(value) => &value.request_id,
            Self::ChooseFolder(value) => &value.request_id,
            Self::ConfirmConfig(value) => &value.request_id,
            Self::RecordVisit(value) => &value.request_id,
            Self::LoadNote(value) => &value.request_id,
            Self::SaveNote(value) => &value.request_id,
            Self::CheckAgent(value) => &value.request_id,
            Self::DiscoverHarnesses(value) => &value.request_id,
            Self::ConfirmHarnessSetup(value) => &value.request_id,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Response {
    HelloResult(HelloResult),
    ConfigResult(ConfigResult),
    ConfigUpdated(ConfigUpdated),
    FolderChosen(FolderChosen),
    ConfigConfirmed(ConfigConfirmed),
    VisitRecorded(VisitRecorded),
    NoteLoaded(NoteLoaded),
    NoteSaved(NoteSaved),
    NoteConflict(NoteConflict),
    AgentChecked(AgentChecked),
    HarnessesDiscovered(HarnessesDiscovered),
    HarnessSetupConfirmed(HarnessSetupConfirmed),
    Error(ErrorResponse),
}

impl Response {
    pub fn protocol_version(&self) -> u32 {
        match self {
            Self::HelloResult(value) => value.protocol_version,
            Self::ConfigResult(value) => value.protocol_version,
            Self::ConfigUpdated(value) => value.protocol_version,
            Self::FolderChosen(value) => value.protocol_version,
            Self::ConfigConfirmed(value) => value.protocol_version,
            Self::VisitRecorded(value) => value.protocol_version,
            Self::NoteLoaded(value) => value.protocol_version,
            Self::NoteSaved(value) => value.protocol_version,
            Self::NoteConflict(value) => value.protocol_version,
            Self::AgentChecked(value) => value.protocol_version,
            Self::HarnessesDiscovered(value) => value.protocol_version,
            Self::HarnessSetupConfirmed(value) => value.protocol_version,
            Self::Error(value) => value.protocol_version,
        }
    }

    pub fn request_id(&self) -> &str {
        match self {
            Self::HelloResult(value) => &value.request_id,
            Self::ConfigResult(value) => &value.request_id,
            Self::ConfigUpdated(value) => &value.request_id,
            Self::FolderChosen(value) => &value.request_id,
            Self::ConfigConfirmed(value) => &value.request_id,
            Self::VisitRecorded(value) => &value.request_id,
            Self::NoteLoaded(value) => &value.request_id,
            Self::NoteSaved(value) => &value.request_id,
            Self::NoteConflict(value) => &value.request_id,
            Self::AgentChecked(value) => &value.request_id,
            Self::HarnessesDiscovered(value) => &value.request_id,
            Self::HarnessSetupConfirmed(value) => &value.request_id,
            Self::Error(value) => &value.request_id,
        }
    }
}
